### PR TITLE
Updated code to be compatible with more recent version of graphite and

### PR DESCRIPTION
**Pull request by Ralnoc**
* Updated code to work with Elasticsearch 1.4.4+ (Old code was including shard information regardless of settings)
* Added log handling to code using a rolling file handler.
* Renamed debug option to dry-run and added log-level option.
* Added stdout option for print log lines
* Removed thread.start_new_thread as it did not provide much functionality improvements and made logging more difficult.

### CODE REVIEW

**Comment by mattweber** [comment]
Thanks, looks good. 

- When in dry run mode, probably don't want to connect to graphite
- The socket should be closed explicitly
- on connect, graphite_socket['port'] is already an int
- I would like to keep support for pickle protocol, maybe make it configurable?

**Comment by Ralnoc** [comment]
There you go. That should resolve those concerns.

**Comment by mattweber** [comment]
Awesome thanks!

**Comment by Ralnoc** [comment]
No problem! And also thank you. This ended up being exactly what I needed. Just needed to fix a couple things. Glad I could help!

**Pull request merged**
